/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Host-side regression test for the synthetic EDID the module hands to
 * compositors.
 *
 * A malformed EDID fails silently in both directions that matter: a bad
 * checksum makes drm_edid_connector_update() drop the block entirely, and a
 * range descriptor narrower than the driver's own mode envelope makes
 * userspace filter modes the connector advertises. Neither shows up as an
 * error at runtime, so pin the generated bytes here.
 *
 * The range decoding below deliberately mirrors mode_in_hsync_range(),
 * mode_in_vsync_range() and get_monitor_range() from drivers/gpu/drm/drm_edid.c
 * rather than the generator, so an inconsistent encoding is caught rather than
 * reproduced.
 */

#include <stdio.h>
#include <stdlib.h>

#include "../kernel/hermes-kms/hermes_kms_edid.h"

static int failures;

#define CHECK(condition, ...)                                                  \
	do {                                                                   \
		if (!(condition)) {                                            \
			failures++;                                            \
			fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);   \
			fprintf(stderr, __VA_ARGS__);                          \
			fprintf(stderr, "\n");                                 \
		}                                                              \
	} while (0)

/* EDID 1.4 feature byte bits the kernel requires before it reads the range. */
#define EDID_FEATURE_CONTINUOUS_FREQ 0x01
#define EDID_FEATURE_PREFERRED_TIMING 0x02

static const u8 edid_header[8] = {
	0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00
};

static u32 decoded_max_vfreq(const u8 *edid)
{
	const u8 *range = &edid[HERMES_KMS_EDID_RANGE_OFFSET];
	u32 value = range[6];

	if (range[4] & HERMES_KMS_EDID_OFFSET_MAX_VFREQ)
		value += 255;
	return value;
}

static u32 decoded_max_hfreq_khz(const u8 *edid)
{
	const u8 *range = &edid[HERMES_KMS_EDID_RANGE_OFFSET];
	u32 value = range[8];

	if (range[4] & HERMES_KMS_EDID_OFFSET_MAX_HFREQ)
		value += 255;
	return value;
}

static void check_structure(const u8 *edid, const char *what)
{
	unsigned int checksum = 0;
	const u8 *range = &edid[HERMES_KMS_EDID_RANGE_OFFSET];
	unsigned int i;

	for (i = 0; i < HERMES_KMS_EDID_SIZE; i++)
		checksum += edid[i];
	CHECK((checksum & 0xff) == 0, "%s: checksum does not sum to zero", what);

	for (i = 0; i < sizeof(edid_header); i++)
		CHECK(edid[i] == edid_header[i],
		      "%s: bad header byte %u", what, i);

	CHECK(edid[HERMES_KMS_EDID_VERSION_OFFSET] == 1 &&
	      edid[HERMES_KMS_EDID_VERSION_OFFSET + 1] == 4,
	      "%s: the +255 range offsets and monitor range need EDID 1.4",
	      what);

	CHECK(edid[HERMES_KMS_EDID_FEATURES_OFFSET] &
	      EDID_FEATURE_CONTINUOUS_FREQ,
	      "%s: drm_get_monitor_range() ignores the range descriptor without the continuous-frequency bit",
	      what);
	CHECK(edid[HERMES_KMS_EDID_FEATURES_OFFSET] &
	      EDID_FEATURE_PREFERRED_TIMING,
	      "%s: first detailed timing must be marked preferred", what);

	/* A display descriptor has a zero pixel clock and a type byte. */
	CHECK(range[0] == 0 && range[1] == 0 && range[2] == 0,
	      "%s: range block is not a display descriptor", what);
	CHECK(range[3] == 0xfd, "%s: range descriptor has the wrong tag", what);
	CHECK(range[10] == HERMES_KMS_EDID_RANGE_LIMITS_ONLY,
	      "%s: only the range-limits-only formula makes the kernel publish a monitor range",
	      what);
	CHECK(range[5] >= 1 && range[5] <= range[6],
	      "%s: vertical range is empty", what);
	CHECK(range[7] >= 1, "%s: minimum horizontal rate must be non-zero",
	      what);
}

static void check_envelope(const struct hermes_kms_edid_config *config,
			   const char *what)
{
	u8 edid[HERMES_KMS_EDID_SIZE];
	bool representable;
	u32 expected_hfreq_khz;
	u64 vtotal;

	representable = hermes_kms_build_edid(edid, 1, config);
	check_structure(edid, what);

	/*
	 * Same blanking model as the generator, but stated independently: the
	 * point is that the encoded descriptor is not narrower than the modes
	 * the driver will accept.
	 */
	vtotal = ((u64)config->max_height * 1000000 +
		  (1000000 - HERMES_KMS_CVT_VBLANK_US * config->max_refresh_hz) - 1) /
		 (1000000 - HERMES_KMS_CVT_VBLANK_US * config->max_refresh_hz);
	expected_hfreq_khz = (u32)((vtotal * config->max_refresh_hz + 999) / 1000);

	if (representable) {
		CHECK(decoded_max_vfreq(edid) >= config->max_refresh_hz,
		      "%s: advertised max %u Hz is below the accepted %u Hz",
		      what, decoded_max_vfreq(edid), config->max_refresh_hz);
		CHECK(decoded_max_hfreq_khz(edid) >= expected_hfreq_khz,
		      "%s: advertised max %u kHz is below the needed %u kHz",
		      what, decoded_max_hfreq_khz(edid), expected_hfreq_khz);
	} else {
		CHECK(decoded_max_hfreq_khz(edid) ==
			      HERMES_KMS_EDID_MAX_HFREQ_KHZ ||
		      decoded_max_vfreq(edid) == HERMES_KMS_EDID_MAX_VFREQ_HZ,
		      "%s: an unrepresentable envelope must still saturate the descriptor",
		      what);
	}
}

static void check_color_depth(void)
{
	static const struct {
		u32 requested;
		u8 expected_field;
	} depths[] = {
		{ 0, 0 }, { 6, 1 }, { 8, 2 }, { 10, 3 },
		{ 12, 4 }, { 14, 5 }, { 16, 6 }, { 9, 0 },
	};
	unsigned int i;

	for (i = 0; i < sizeof(depths) / sizeof(depths[0]); i++) {
		struct hermes_kms_edid_config config = {
			.max_width = 1920,
			.max_height = 1080,
			.max_refresh_hz = 60,
			.color_depth = depths[i].requested,
		};
		u8 edid[HERMES_KMS_EDID_SIZE];
		u8 video_input;

		hermes_kms_build_edid(edid, 1, &config);
		check_structure(edid, "colour depth");

		video_input = edid[HERMES_KMS_EDID_VIDEO_INPUT_OFFSET];
		CHECK(video_input & 0x80,
		      "depth %u: the input must stay digital",
		      depths[i].requested);
		CHECK(((video_input >> 4) & 0x07) == depths[i].expected_field,
		      "depth %u: encoded field is %u, expected %u",
		      depths[i].requested, (video_input >> 4) & 0x07,
		      depths[i].expected_field);
		CHECK((video_input & 0x0f) == 0,
		      "depth %u: the digital interface must stay undefined",
		      depths[i].requested);
	}
}

/*
 * Validate the CTA-861 extension block (the second EDID block) independently of
 * the builder, mirroring how an EDID parser would decode it rather than reusing
 * hermes_kms_build_edid_hdr_extension()'s own constants, so an inconsistent
 * generator is caught instead of reproduced.
 *
 * Exercises Property 2 (the block sums to 0 mod 256), Property 4 (the EOTF byte
 * sets the traditional-SDR-gamma and SMPTE ST2084/PQ bits together and never PQ
 * without SDR gamma), and Property 6 (the HDR data block identity: a
 * use-extended-tag data block with extended tag 0x06 declaring Static Metadata
 * Descriptor Type 1).
 *
 * It also exercises Property 10 (the Colorimetry data block at bytes 8..11 is
 * well-formed: 0xE3, 0x05, 0x80, 0x00), Property 11 (both data blocks are
 * present and the DTD offset points past them at 12), and Property 12 (the CTA
 * checksum sums to 0 mod 256 with both data blocks present -- the checksum
 * check above now covers both blocks).
 */
static void check_cta_extension(const u8 *block, const char *what)
{
	unsigned int checksum = 0;
	u8 tag_length;
	u8 payload_length;
	u8 eotf;
	unsigned int i;

	for (i = 0; i < HERMES_KMS_EDID_SIZE; i++)
		checksum += block[i];
	CHECK((checksum & 0xff) == 0,
	      "%s: CTA extension checksum does not sum to zero", what);

	/*
	 * CTA-861 extension header: tag 0x02, DTD offset 12 (no detailed
	 * timings; the offset points past the 4-byte CTA header plus the two
	 * 4-byte data blocks that make up the 8-byte data block collection).
	 */
	CHECK(block[0] == 0x02,
	      "%s: CTA extension tag is 0x%02x, expected 0x02", what, block[0]);
	CHECK(block[2] == 0x0c,
	      "%s: CTA DTD offset is 0x%02x, expected 0x0c (no detailed timings, past both data blocks)",
	      what, block[2]);

	/*
	 * The data block collection starts at byte 4. Decode the tag/length
	 * byte the way CTA-861 specifies: bits 7:5 are the block type and bits
	 * 4:0 the number of payload bytes that follow.
	 */
	tag_length = block[4];
	payload_length = tag_length & 0x1f;
	CHECK((tag_length >> 5) == 0x07,
	      "%s: data block type is %u, expected 0x07 (use extended tag)",
	      what, tag_length >> 5);
	CHECK(payload_length == 3,
	      "%s: HDR data block declares %u payload bytes, expected 3",
	      what, payload_length);

	/* Extended tag 0x06 identifies the block as HDR Static Metadata. */
	CHECK(block[5] == 0x06,
	      "%s: extended tag is 0x%02x, expected 0x06 (HDR static metadata)",
	      what, block[5]);

	/*
	 * EOTF byte: bit 0 is traditional SDR gamma, bit 2 is SMPTE ST2084
	 * (PQ). Both must be set (0x05), and PQ must never appear without SDR
	 * gamma.
	 */
	eotf = block[6];
	CHECK(eotf == 0x05,
	      "%s: EOTF byte is 0x%02x, expected 0x05 (SDR gamma + ST2084/PQ)",
	      what, eotf);
	CHECK(eotf & 0x01,
	      "%s: traditional SDR gamma EOTF bit must be set", what);
	CHECK(eotf & 0x04,
	      "%s: SMPTE ST2084 (PQ) EOTF bit must be set", what);
	CHECK(!(eotf & 0x04) || (eotf & 0x01),
	      "%s: PQ EOTF must never be set without SDR gamma", what);

	/* Descriptor byte declares Static Metadata Descriptor Type 1. */
	CHECK(block[7] == 0x01,
	      "%s: descriptor type byte is 0x%02x, expected 0x01",
	      what, block[7]);

	/*
	 * The Colorimetry Data Block follows immediately at bytes 8..11.
	 * Decode its tag/length byte the same way as the HDR block above: bits
	 * 7:5 are the block type (0x07, use extended tag) and bits 4:0 the
	 * payload length (3 bytes following).
	 */
	tag_length = block[8];
	payload_length = tag_length & 0x1f;
	CHECK((tag_length >> 5) == 0x07,
	      "%s: colorimetry block type is %u, expected 0x07 (use extended tag)",
	      what, tag_length >> 5);
	CHECK(payload_length == 3,
	      "%s: colorimetry block declares %u payload bytes, expected 3",
	      what, payload_length);

	/* Extended tag 0x05 identifies the block as Colorimetry. */
	CHECK(block[9] == 0x05,
	      "%s: colorimetry extended tag is 0x%02x, expected 0x05",
	      what, block[9]);

	/*
	 * Colorimetry byte: bit 7 is BT2020 RGB. It must be the only bit set,
	 * so the whole byte reads 0x80 -- KWin's supportsBT2020() only checks
	 * for BT2020 RGB and the block advertises nothing else.
	 */
	CHECK(block[10] == 0x80,
	      "%s: colorimetry byte is 0x%02x, expected 0x80 (BT2020 RGB only)",
	      what, block[10]);
	CHECK(block[10] & 0x80,
	      "%s: BT2020 RGB colorimetry bit must be set", what);

	/* Gamut-metadata byte advertises no supported bits. */
	CHECK(block[11] == 0x00,
	      "%s: gamut-metadata byte is 0x%02x, expected 0x00",
	      what, block[11]);
}

/*
 * Validate the two-block coupling between the base block and the appended CTA
 * extension. Build a single-block base EDID, record its pre-append checksum,
 * then promote it with hermes_kms_append_hdr_extension() and check that the
 * base block is still well-formed while the extension-count and checksum bytes
 * moved together.
 *
 * Exercises Property 1 (the base block sums to 0 mod 256 both before and after
 * the extension is appended -- check_structure() re-runs the base-block
 * checks), Property 3 (base byte 126 becomes 1 and base byte 127 becomes its
 * pre-append value minus 1 mod 256), and Property 5 (the appended extension
 * block is exactly HERMES_KMS_EDID_SIZE bytes and the whole buffer is exactly
 * 2 * HERMES_KMS_EDID_SIZE bytes). check_cta_extension() covers the extension
 * block's own well-formedness.
 */
static void check_base_with_extension(const struct hermes_kms_edid_config *config,
				      const char *what)
{
	u8 edid[2 * HERMES_KMS_EDID_SIZE];
	u8 pre_append_checksum;
	bool appended;

	CHECK(sizeof(edid) == 2 * HERMES_KMS_EDID_SIZE,
	      "%s: EDID buffer must be exactly two blocks", what);

	hermes_kms_build_edid(edid, 1, config);

	/* The base block must be valid before the extension is appended. */
	check_structure(edid, what);
	CHECK(edid[HERMES_KMS_EDID_EXT_COUNT_OFFSET] == 0,
	      "%s: single-block base must have extension count 0", what);
	pre_append_checksum = edid[HERMES_KMS_EDID_CHECKSUM_OFFSET];

	appended = hermes_kms_append_hdr_extension(edid);
	CHECK(appended, "%s: appending the extension to a valid base must succeed",
	      what);

	/* Property 1: the base block is still well-formed after the append. */
	check_structure(edid, what);

	/* Property 3: extension-count and checksum move together. */
	CHECK(edid[HERMES_KMS_EDID_EXT_COUNT_OFFSET] == 1,
	      "%s: base extension count is %u, expected 1", what,
	      edid[HERMES_KMS_EDID_EXT_COUNT_OFFSET]);
	CHECK(edid[HERMES_KMS_EDID_CHECKSUM_OFFSET] ==
		      (u8)(pre_append_checksum - 1),
	      "%s: base checksum is 0x%02x, expected 0x%02x (pre-append minus 1)",
	      what, edid[HERMES_KMS_EDID_CHECKSUM_OFFSET],
	      (u8)(pre_append_checksum - 1));

	/* Property 5 / Property 2,4,6: the appended extension block is valid. */
	check_cta_extension(&edid[HERMES_KMS_EDID_SIZE], what);
}

/*
 * Validate the finalize guard: a base block that does not already sum to 0 mod
 * 256 is not a valid EDID, and promoting it into a two-block EDID would only
 * produce a broken result. So hermes_kms_append_hdr_extension() must refuse a
 * corrupt base and leave the extension region exactly as it found it.
 *
 * Build a valid base, paint the extension region (edid[128..255]) with a known
 * sentinel pattern and snapshot it, then deliberately corrupt one base byte so
 * the base no longer sums to 0 mod 256. The append must return false and the
 * extension region must be byte-identical to the snapshot afterwards.
 *
 * Exercises Property 7 (finalize refuses an invalid base and does not touch the
 * extension region).
 */
static void check_invalid_base_refused(const struct hermes_kms_edid_config *config,
				       const char *what)
{
	u8 edid[2 * HERMES_KMS_EDID_SIZE];
	u8 snapshot[HERMES_KMS_EDID_SIZE];
	unsigned int checksum = 0;
	bool appended;
	unsigned int i;

	hermes_kms_build_edid(edid, 1, config);

	/*
	 * Fill the extension region with a recognisable pattern and snapshot it
	 * so a refused append is provably a no-op there rather than merely
	 * leaving zeroes behind.
	 */
	for (i = 0; i < HERMES_KMS_EDID_SIZE; i++) {
		u8 pattern = (u8)(0xa5 ^ i);

		edid[HERMES_KMS_EDID_SIZE + i] = pattern;
		snapshot[i] = pattern;
	}

	/*
	 * Corrupt the base so it no longer sums to 0 mod 256. Flipping the low
	 * bit of the first byte perturbs the sum by exactly 1, guaranteeing an
	 * invalid checksum without depending on any other byte.
	 */
	edid[0] ^= 0x01;
	for (i = 0; i < HERMES_KMS_EDID_SIZE; i++)
		checksum += edid[i];
	CHECK((checksum & 0xff) != 0,
	      "%s: corrupted base must not sum to zero", what);

	appended = hermes_kms_append_hdr_extension(edid);
	CHECK(!appended,
	      "%s: appending to an invalid base must fail", what);

	/* The extension region must be untouched byte-for-byte. */
	for (i = 0; i < HERMES_KMS_EDID_SIZE; i++)
		CHECK(edid[HERMES_KMS_EDID_SIZE + i] == snapshot[i],
		      "%s: extension byte %u changed to 0x%02x, expected 0x%02x",
		      what, i, edid[HERMES_KMS_EDID_SIZE + i], snapshot[i]);
}

/*
 * Validate the HDR-disabled path. With hdr_enable off the driver never calls
 * hermes_kms_append_hdr_extension(), so the EDID it publishes is exactly the
 * single base block hermes_kms_build_edid() produces: extension-count byte 0
 * and a base block that stands on its own. This check builds precisely that --
 * the base block with no append -- so it is byte-identical to the pre-feature
 * output, and confirms the extension-count byte stays 0.
 *
 * Exercises Property 8 (the disabled path is byte-identical to the base-only
 * EDID: a single base block with extension-count byte 0).
 */
static void check_hdr_disabled_base_only(const struct hermes_kms_edid_config *config,
					 const char *what)
{
	u8 edid[HERMES_KMS_EDID_SIZE];

	/*
	 * This is the disabled path exactly: build the base block and stop.
	 * No hermes_kms_append_hdr_extension() call, matching what the driver
	 * hands DRM when hdr_enable is off.
	 */
	hermes_kms_build_edid(edid, 1, config);

	check_structure(edid, what);
	CHECK(edid[HERMES_KMS_EDID_EXT_COUNT_OFFSET] == 0,
	      "%s: disabled path must leave extension count 0, got %u", what,
	      edid[HERMES_KMS_EDID_EXT_COUNT_OFFSET]);
}

static void check_serials_differ(void)
{
	const struct hermes_kms_edid_config config = {
		.max_width = 3840,
		.max_height = 2160,
		.max_refresh_hz = 240,
	};
	u8 first[HERMES_KMS_EDID_SIZE];
	u8 second[HERMES_KMS_EDID_SIZE];
	unsigned int i;
	bool differs = false;

	hermes_kms_build_edid(first, 1, &config);
	hermes_kms_build_edid(second, 2, &config);
	check_structure(first, "serial 1");
	check_structure(second, "serial 2");

	for (i = 0; i < 4; i++) {
		if (first[HERMES_KMS_EDID_SERIAL_OFFSET + i] !=
		    second[HERMES_KMS_EDID_SERIAL_OFFSET + i])
			differs = true;
	}
	CHECK(differs,
	      "outputs must carry distinct EDID serials so compositors can persist a layout");
}

static void check_physical_size(void)
{
	struct hermes_kms_edid_config config = {
		.max_width = 1920,
		.max_height = 1080,
		.max_refresh_hz = 60,
	};
	u8 edid[HERMES_KMS_EDID_SIZE];
	const u8 *dtd;
	u32 dtd_width_mm;
	u32 dtd_height_mm;

	hermes_kms_build_edid(edid, 1, &config);
	check_structure(edid, "undefined size");
	CHECK(edid[HERMES_KMS_EDID_SIZE_CM_OFFSET] == 0 &&
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET + 1] == 0,
	      "an unset physical size must stay undefined");

	config.physical_width_mm = 697;
	config.physical_height_mm = 392;
	hermes_kms_build_edid(edid, 1, &config);
	check_structure(edid, "defined size");

	dtd = &edid[HERMES_KMS_EDID_DTD_OFFSET];
	dtd_width_mm = dtd[12] | ((u32)(dtd[14] >> 4) << 8);
	dtd_height_mm = dtd[13] | ((u32)(dtd[14] & 0x0f) << 8);
	CHECK(dtd_width_mm == 697 && dtd_height_mm == 392,
	      "detailed timing size is %ux%u mm, expected 697x392",
	      dtd_width_mm, dtd_height_mm);
	CHECK(edid[HERMES_KMS_EDID_SIZE_CM_OFFSET] == 70 &&
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET + 1] == 39,
	      "base block size is %ux%u cm, expected 70x39",
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET],
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET + 1]);
}

int main(void)
{
	static const struct {
		const char *what;
		struct hermes_kms_edid_config config;
	} envelopes[] = {
#define ENVELOPE(w, h, hz) \
	{ .max_width = (w), .max_height = (h), .max_refresh_hz = (hz) }
		{ "1080p60", ENVELOPE(1920, 1080, 60) },
		{ "1080p240", ENVELOPE(1920, 1080, 240) },
		{ "1440p144", ENVELOPE(2560, 1440, 144) },
		{ "ultrawide", ENVELOPE(5120, 1440, 240) },
		{ "4k120", ENVELOPE(3840, 2160, 120) },
		{ "default envelope", ENVELOPE(7680, 4320, 240) },
		{ "tiny", ENVELOPE(640, 480, 1) },
		{ "extreme", ENVELOPE(16384, 16384, 1000) },
#undef ENVELOPE
	};
	unsigned int i;

	for (i = 0; i < sizeof(envelopes) / sizeof(envelopes[0]); i++)
		check_envelope(&envelopes[i].config, envelopes[i].what);

	check_serials_differ();
	check_physical_size();
	check_color_depth();

	{
		u8 cta[HERMES_KMS_EDID_SIZE];

		hermes_kms_build_edid_hdr_extension(cta);
		check_cta_extension(cta, "CTA HDR extension");
	}

	/*
	 * Sweep the two-block HDR checks across a small table of distinct
	 * configs the same way check_envelope() sweeps envelopes[], so the
	 * base/extension invariants (Properties 1-8) hold across the input
	 * space rather than for a single hand-picked resolution.
	 */
	{
		static const struct {
			const char *what;
			struct hermes_kms_edid_config config;
		} hdr_configs[] = {
#define HDR_CONFIG(w, h, hz) \
	{ .max_width = (w), .max_height = (h), .max_refresh_hz = (hz) }
			{ "hdr 1080p60", HDR_CONFIG(1920, 1080, 60) },
			{ "hdr 1440p144", HDR_CONFIG(2560, 1440, 144) },
			{ "hdr 4k120", HDR_CONFIG(3840, 2160, 120) },
			{ "hdr 4k240", HDR_CONFIG(3840, 2160, 240) },
#undef HDR_CONFIG
		};
		unsigned int j;

		for (j = 0; j < sizeof(hdr_configs) / sizeof(hdr_configs[0]);
		     j++) {
			check_base_with_extension(&hdr_configs[j].config,
						  hdr_configs[j].what);
			check_invalid_base_refused(&hdr_configs[j].config,
						   hdr_configs[j].what);
			check_hdr_disabled_base_only(&hdr_configs[j].config,
						     hdr_configs[j].what);
		}
	}

	if (failures) {
		fprintf(stderr, "%d EDID check(s) failed\n", failures);
		return EXIT_FAILURE;
	}
	return EXIT_SUCCESS;
}
