/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Host-side regression test for the synthetic EDID the module hands to
 * compositors.
 *
 * A malformed EDID fails silently in both directions that matter: a bad
 * checksum makes drm_edid_connector_update() drop the block entirely, and a
 * range descriptor narrower than the driver's own mode envelope makes
 * userspace filter modes the connector advertises. Neither shows up as an
 * error at runtime, so pin the generated bytes here.
 *
 * The range decoding below deliberately mirrors mode_in_hsync_range(),
 * mode_in_vsync_range() and get_monitor_range() from drivers/gpu/drm/drm_edid.c
 * rather than the generator, so an inconsistent encoding is caught rather than
 * reproduced.
 */

#include <stdio.h>
#include <stdlib.h>

#include "../kernel/hermes-kms/hermes_kms_edid.h"

static int failures;

#define CHECK(condition, ...)                                                  \
	do {                                                                   \
		if (!(condition)) {                                            \
			failures++;                                            \
			fprintf(stderr, "FAIL %s:%d: ", __FILE__, __LINE__);   \
			fprintf(stderr, __VA_ARGS__);                          \
			fprintf(stderr, "\n");                                 \
		}                                                              \
	} while (0)

/* EDID 1.4 feature byte bits the kernel requires before it reads the range. */
#define EDID_FEATURE_CONTINUOUS_FREQ 0x01
#define EDID_FEATURE_PREFERRED_TIMING 0x02

static const u8 edid_header[8] = {
	0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00
};

static u32 decoded_max_vfreq(const u8 *edid)
{
	const u8 *range = &edid[HERMES_KMS_EDID_RANGE_OFFSET];
	u32 value = range[6];

	if (range[4] & HERMES_KMS_EDID_OFFSET_MAX_VFREQ)
		value += 255;
	return value;
}

static u32 decoded_max_hfreq_khz(const u8 *edid)
{
	const u8 *range = &edid[HERMES_KMS_EDID_RANGE_OFFSET];
	u32 value = range[8];

	if (range[4] & HERMES_KMS_EDID_OFFSET_MAX_HFREQ)
		value += 255;
	return value;
}

static void check_structure(const u8 *edid, const char *what)
{
	unsigned int checksum = 0;
	const u8 *range = &edid[HERMES_KMS_EDID_RANGE_OFFSET];
	unsigned int i;

	for (i = 0; i < HERMES_KMS_EDID_SIZE; i++)
		checksum += edid[i];
	CHECK((checksum & 0xff) == 0, "%s: checksum does not sum to zero", what);

	for (i = 0; i < sizeof(edid_header); i++)
		CHECK(edid[i] == edid_header[i],
		      "%s: bad header byte %u", what, i);

	CHECK(edid[HERMES_KMS_EDID_VERSION_OFFSET] == 1 &&
	      edid[HERMES_KMS_EDID_VERSION_OFFSET + 1] == 4,
	      "%s: the +255 range offsets and monitor range need EDID 1.4",
	      what);

	CHECK(edid[HERMES_KMS_EDID_FEATURES_OFFSET] &
	      EDID_FEATURE_CONTINUOUS_FREQ,
	      "%s: drm_get_monitor_range() ignores the range descriptor without the continuous-frequency bit",
	      what);
	CHECK(edid[HERMES_KMS_EDID_FEATURES_OFFSET] &
	      EDID_FEATURE_PREFERRED_TIMING,
	      "%s: first detailed timing must be marked preferred", what);

	/* A display descriptor has a zero pixel clock and a type byte. */
	CHECK(range[0] == 0 && range[1] == 0 && range[2] == 0,
	      "%s: range block is not a display descriptor", what);
	CHECK(range[3] == 0xfd, "%s: range descriptor has the wrong tag", what);
	CHECK(range[10] == HERMES_KMS_EDID_RANGE_LIMITS_ONLY,
	      "%s: only the range-limits-only formula makes the kernel publish a monitor range",
	      what);
	CHECK(range[5] >= 1 && range[5] <= range[6],
	      "%s: vertical range is empty", what);
	CHECK(range[7] >= 1, "%s: minimum horizontal rate must be non-zero",
	      what);
}

static void check_envelope(const struct hermes_kms_edid_limits *limits,
			   const char *what)
{
	u8 edid[HERMES_KMS_EDID_SIZE];
	bool representable;
	u32 expected_hfreq_khz;
	u64 vtotal;

	representable = hermes_kms_build_edid(edid, 1, limits);
	check_structure(edid, what);

	/*
	 * Same blanking model as the generator, but stated independently: the
	 * point is that the encoded descriptor is not narrower than the modes
	 * the driver will accept.
	 */
	vtotal = ((u64)limits->max_height * 1000000 +
		  (1000000 - HERMES_KMS_CVT_VBLANK_US * limits->max_refresh_hz) - 1) /
		 (1000000 - HERMES_KMS_CVT_VBLANK_US * limits->max_refresh_hz);
	expected_hfreq_khz = (u32)((vtotal * limits->max_refresh_hz + 999) / 1000);

	if (representable) {
		CHECK(decoded_max_vfreq(edid) >= limits->max_refresh_hz,
		      "%s: advertised max %u Hz is below the accepted %u Hz",
		      what, decoded_max_vfreq(edid), limits->max_refresh_hz);
		CHECK(decoded_max_hfreq_khz(edid) >= expected_hfreq_khz,
		      "%s: advertised max %u kHz is below the needed %u kHz",
		      what, decoded_max_hfreq_khz(edid), expected_hfreq_khz);
	} else {
		CHECK(decoded_max_hfreq_khz(edid) ==
			      HERMES_KMS_EDID_MAX_HFREQ_KHZ ||
		      decoded_max_vfreq(edid) == HERMES_KMS_EDID_MAX_VFREQ_HZ,
		      "%s: an unrepresentable envelope must still saturate the descriptor",
		      what);
	}
}

static void check_serials_differ(void)
{
	const struct hermes_kms_edid_limits limits = {
		.max_width = 3840,
		.max_height = 2160,
		.max_refresh_hz = 240,
	};
	u8 first[HERMES_KMS_EDID_SIZE];
	u8 second[HERMES_KMS_EDID_SIZE];
	unsigned int i;
	bool differs = false;

	hermes_kms_build_edid(first, 1, &limits);
	hermes_kms_build_edid(second, 2, &limits);
	check_structure(first, "serial 1");
	check_structure(second, "serial 2");

	for (i = 0; i < 4; i++) {
		if (first[HERMES_KMS_EDID_SERIAL_OFFSET + i] !=
		    second[HERMES_KMS_EDID_SERIAL_OFFSET + i])
			differs = true;
	}
	CHECK(differs,
	      "outputs must carry distinct EDID serials so compositors can persist a layout");
}

static void check_physical_size(void)
{
	struct hermes_kms_edid_limits limits = {
		.max_width = 1920,
		.max_height = 1080,
		.max_refresh_hz = 60,
	};
	u8 edid[HERMES_KMS_EDID_SIZE];
	const u8 *dtd;
	u32 dtd_width_mm;
	u32 dtd_height_mm;

	hermes_kms_build_edid(edid, 1, &limits);
	check_structure(edid, "undefined size");
	CHECK(edid[HERMES_KMS_EDID_SIZE_CM_OFFSET] == 0 &&
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET + 1] == 0,
	      "an unset physical size must stay undefined");

	limits.physical_width_mm = 697;
	limits.physical_height_mm = 392;
	hermes_kms_build_edid(edid, 1, &limits);
	check_structure(edid, "defined size");

	dtd = &edid[HERMES_KMS_EDID_DTD_OFFSET];
	dtd_width_mm = dtd[12] | ((u32)(dtd[14] >> 4) << 8);
	dtd_height_mm = dtd[13] | ((u32)(dtd[14] & 0x0f) << 8);
	CHECK(dtd_width_mm == 697 && dtd_height_mm == 392,
	      "detailed timing size is %ux%u mm, expected 697x392",
	      dtd_width_mm, dtd_height_mm);
	CHECK(edid[HERMES_KMS_EDID_SIZE_CM_OFFSET] == 70 &&
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET + 1] == 39,
	      "base block size is %ux%u cm, expected 70x39",
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET],
	      edid[HERMES_KMS_EDID_SIZE_CM_OFFSET + 1]);
}

int main(void)
{
	static const struct {
		const char *what;
		struct hermes_kms_edid_limits limits;
	} envelopes[] = {
		{ "1080p60", { 1920, 1080, 60, 0, 0 } },
		{ "1080p240", { 1920, 1080, 240, 0, 0 } },
		{ "1440p144", { 2560, 1440, 144, 0, 0 } },
		{ "ultrawide", { 5120, 1440, 240, 0, 0 } },
		{ "4k120", { 3840, 2160, 120, 0, 0 } },
		{ "default envelope", { 7680, 4320, 240, 0, 0 } },
		{ "tiny", { 640, 480, 1, 0, 0 } },
		{ "extreme", { 16384, 16384, 1000, 0, 0 } },
	};
	unsigned int i;

	for (i = 0; i < sizeof(envelopes) / sizeof(envelopes[0]); i++)
		check_envelope(&envelopes[i].limits, envelopes[i].what);

	check_serials_differ();
	check_physical_size();

	if (failures) {
		fprintf(stderr, "%d EDID check(s) failed\n", failures);
		return EXIT_FAILURE;
	}
	return EXIT_SUCCESS;
}
